name: Docker Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        tags: ghcr.io/aidancrowther/milk-v-duo-docker-compile:latest
        context: .
        push: false

    - name: Run Commands from Outside the Container example
      run: docker run -t \
        -v $(pwd):/home/milkv/buildroot \
        ghcr.io/aidancrowther/milk-v-duo-docker-compile:latest \
        bash -c "cd examples/hello-world && make"

    - name: Test sudo
      run: docker run -t \
        -v $(pwd):/home/milkv/buildroot \
        ghcr.io/aidancrowther/milk-v-duo-docker-compile:latest \
        bash -c "echo milk | sudo -S apt-get update"
